use_frameworks!

platform :ios, '9.0'

target 'MSBlinkingLabel_Example' do
  pod 'MSBlinkingLabel', :path => '../', 'ReleaseBeta' => :release
  

  target 'MSBlinkingLabel_Tests' do
    inherit! :search_paths

    
  end
end
